[notify]
debug_output=false

[notify.email]
port=25
use_tls=false
use_ssl=false
subject="[Toptal Notifier] {n} jobs found for you"

[notify.persist]
path="persist.toml"

[notify.tags]
filter=false
exclude=[]
include=[]

[notify.tz]
filter=false
home="UTC"
shift_early=0
shift_late=0
